language: python
os:
  - linux
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
sudo: true
services:
  - docker
before_install:
  - docker version
install:
  - pip install -U pip
  - pip install coverage
  - pip install codacy-coverage
  - pip install -e .[test]
script:
  - py.test --flake8 --cov=boatswain $TESTS
after_success:
 - coverage xml
 - python-codacy-coverage -r coverage.xml
