language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
sudo: true
env:
  - DOCKER_VERSION=1.11.0
  - DOCKER_VERSION=1.12.0
  - DOCKER_VERSION=17.05.0
services:
  - docker
before_install:
  - sudo apt-get install docker=$DOCKER_VERSION
  - docker version
install:
  - pip install -U pip
  - pip install -r requirements.txt .
script:
  - pytest --flake8 $TESTS
