language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: true
services:
  - docker
before_install:
  - docker version
install:
  - pip install -U pip
  - pip install -e .[test]
script:
  - py.test --flake8 $TESTS
