language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: true
services:
  - docker
before_install:
  - docker version
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
install:
  - pip install -U pip
  - pip install coverage
  - pip install codacy-coverage
  - pip install -e .[test]
script:
  - py.test --flake8 $TESTS
after_success:
 - coverage xml
 - python-codacy-coverage -r coverage.xml
