language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
sudo: true
addons:
  apt:
    sources:
      - sourceline: 'deb https://apt.dockerproject.org/repo ubuntu-trusty main'
env:
  - DOCKER_VERSION=1.11.0-0~trusty
  - DOCKER_VERSION=1.12.0-0~trusty
  - DOCKER_VERSION=17.05.0~ce-0~ubuntu-trusty
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install apt-transport-https ca-certificates
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-get update
  - sudo apt-get install -y docker-engine=$DOCKER_VERSION
  - sudo service docker restart
  - docker version
install:
  - pip install -U pip
  - pip install -r requirements.txt .
script:
  - pytest --flake8 $TESTS
