version: '{branch}-{build}'
image: Visual Studio 2017

environment:
  matrix:
    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    # See: http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x" # currently 2.7.13
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x" # currently 2.7.13
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.x" # currently 3.4.4
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x" # currently 3.4.4
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.5.x" # currently 3.5.3
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.5.x" # currently 3.5.3
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.6.x" # currently 3.6.1
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.6.x" # currently 3.6.1
      PYTHON_ARCH: "64"

build_script:
  # Build the compiled extension
  - "%CMD_IN_ENV% pip install -e .[test,windows]"

install:
  - docker version
  - docker images -a
  # Add python things to the path
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

test_script:
  # Run the project tests
  - "%CMD_IN_ENV% py.test --flake8 --cov=boatswain test/"